name: RuboCop

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [head, 3.0.0, 2.7.2, 2.6.6, 2.5.8, 2.5.1]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install rubocop gem
      run: gem install rubocop

    - name: Run RuboCop
      run: rubocop
